### ISSUE TITLE
"errorCode":"5","errorMessage":"Access denied"

### ISSUE THREAD

**Issue by Rest00rer** [MadBrains/Sberbank-Acquiring-SDK-Flutter#7]
`[Sber|Request URL] https://securepayments.sberbank.ru/payment/rest/register.do
[Sber|Request headers] {content-type: application/x-www-form-urlencoded}
[Sber|RawRequest] {orderNumber: test, amount: 15100, returnUrl: https://test.ru/return.html, pageView: MOBILE, userName: T2**********0-api, password: T2**********0}
[Sber|RawResponse] 200 | {"errorCode":"5","errorMessage":"Access denied"}
[Sber|RawResponse] {"errorCode":"5","errorMessage":"Access denied"}
[Sber|Response] RegisterResponse(errorCode: 5, errorMessage: Access denied, orderId: null, formUrl: null, externalParams: null)`
В чем может быть проблема? Логин/пароль отправляю корректный

**Comment by mit-73** [comment]
Здравствуйте, вы пробовали использовать token вместо userName/password?

**Comment by Rest00rer** [comment]
> Здравствуйте, вы пробовали использовать token вместо userName/password?

Проблему исправил. Нужно было включить debug mod (isDebugMode: true,)
